# Generated by Django 5.1.5 on 2025-02-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cats", "0002_auto_20250202_1433"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breed",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="cat",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
