# Generated by Django 4.2.5 on 2025-02-21 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pic',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pic',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='pic',
            name='text',
        ),
        migrations.RemoveField(
            model_name='pic',
            name='title',
        ),
        migrations.RemoveField(
            model_name='pic',
            name='updated_at',
        ),
    ]
